# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    # docker:
      # - image: cimg/node:17.4.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    machine: true
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Build
          command: |
            docker build nginx -t twilio-proxy:latest
            docker rm --force twilio-proxy
            docker run -p 127.0.0.1:443:443 -d --rm --name twilio-proxy twilio-proxy:latest
      - run:
          name: Start Proxy
          command: yarn proxy
      - run:
          name: Start Server
          command: yarn start:prod
      - run:
          name: Run Tests
          command: yarn tests
      - run:
          name: Stop Proxy
          command: |
            docker rm --force twilio-proxy


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - test
