# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Start containers
    - run: yarn
      run: yarn proxy
    - run: yarn build
    - run: |
        "nohup yarn start:prod &"
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 api.local.twilio.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 conversations.local.twilio.com" | sudo tee -a /etc/hosts
    - run: yarn test
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
